version: 2
jobs:
    build:
        working_directory: ~/my-project
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install Node v10.15.1
                  command: |
                      sudo chmod +x ./.circleci/load-nvm.sh
                      ./.circleci/load-nvm.sh
                      nvm install v10.15.1
                      nvm alias default v10.15.1
            - run:
                  name: Install dependencies
                  command: |
                      ./.circleci/load-nvm.sh
                      npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Jest component tests
                  command: |
                      ./.circleci/load-nvm.sh
                      npm run bootstrap; npm run component-test-jest
            - run:
                  name: Jest end-to-end tests
                  command: |
                      ./.circleci/load-nvm.sh
                      npm run bootstrap; npm run e2e-test-jest
            - run:
                  name: Muppeteer component tests
                  command: |
                      ./.circleci/load-nvm.sh
                      npm run bootstrap; npm run component-test-muppeteer
            - run:
                  name: Muppeteer end-to-end tests
                  command: |
                      ./.circleci/load-nvm.sh
                      npm run bootstrap; npm run e2e-test-muppeteer
