version: 2
jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - setup_remote_docker
            - run:
                  name: Jest component tests
                  command: npm run bootstrap; npm run component-test-jest
            - run:
                  name: Jest end-to-end tests
                  command: npm run bootstrap; npm run e2e-test-jest
            - run:
                  name: Muppeteer component tests
                  command: npm run bootstrap; npm run component-test-muppeteer
            - run:
                  name: Muppeteer end-to-end tests
                  command: npm run bootstrap; npm run e2e-test-muppeteer
