version: 2
jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install NVM
                  command: |
                      export NVM_DIR="/opt/circleci/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      nvm install v8.11.3
                      nvm alias default v8.11.3
            - run: |
                  export NVM_DIR="/opt/circleci/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install v8.11.3
                  nvm alias default v8.11.3
            - run: |
                  export NVM_DIR="/opt/circleci/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install v8.11.3
                  nvm alias default v8.11.3
                  npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Jest component tests
                  command: |
                      export NVM_DIR="/opt/circleci/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      nvm install v8.11.3
                      nvm alias default v8.11.3
                      npm run bootstrap; npm run component-test-jest
