version: 2
jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install NVM
                  command: |
                      ./load-nvm.sh
                      nvm install v8.11.3
                      nvm alias default v8.11.3
            - run: |
                  ./load-nvm.sh
                  npm version
