version: 2
jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install NVM
                  command: |
                      set +e
                      touch $BASH_ENV
                      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
                      echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
                      echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
                      echo 'nvm install v10.15.1' >> $BASH_ENV
                      echo 'nvm alias default v10.15.1' >> $BASH_ENV
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Jest component tests
                  command: npm run bootstrap; npm run component-test-jest
            - run:
                  name: Jest end-to-end tests
                  command: npm run bootstrap; npm run e2e-test-jest
            - run:
                  name: Muppeteer component tests
                  command: npm run bootstrap; npm run component-test-muppeteer
            - run:
                  name: Muppeteer end-to-end tests
                  command: npm run bootstrap; npm run e2e-test-muppeteer
